name: React Firebase CI/CD

on:
  push:
    braches:
      - main

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use node v16
        uses: actions/setup-node@v3
        with:
          node-version: "16.18"

      - name: Install Dependencies
        run: npm install

      - name: Test project
        run: npm run test

  build:
    name: Build
    # run only if test success
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use node v16
        uses: actions/setup-node@v3
        with:
          node-version: "16.18"

      - name: Install Dependencies
        run: npm install

      - name: Build project
        run: npm run build
      # create artifact
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    name: Deploy app
    # run only if build success
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use node v16
        uses: actions/setup-node@v3
        with:
          node-version: "16.18"
      # use artifact
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
